---
- name: Create users and download tomcat and install tomcat
  become: yes
  hosts: all
  vars:
   - apache_pacakage: apache2
   - sql_pacakge: mysql-server
  tasks:
   - name: install apache server
     package:
      name: "{{ apache_pacakage }}"
      state: present
   - name: allow traffic on port 80 for apache
     community.general.ufw:
      name: 'apache'
      rule: allow
      port: '80'
      proto: tcp
      state: enabled 
   - name: install SQL server
     package:
      name: "{{ sql_pacakge }}"
      state: present